/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


 /* Includes the header in the wrapper code */
#include "api/yajl_common.h"
#include "api/yajl_gen.h"
#include "api/yajl_parse.h"
#include "api/yajl_tree.h"
 
typedef union {
  char * string;
  struct {
    long long i;                                        
    double  d;                                         
    
    char   *r;                                         
    unsigned int flags;
  } number;
  struct {
    const char **keys;                     
    yajl_val *values;                        
    size_t len;                                  
  } object;
  struct {
    yajl_val *values;                          
    size_t len;                           
  } array;
} yajl_val_s_u;


typedef struct {
  long long i;                                        
  double  d;                                         
  
  char   *r;                                         
  unsigned int flags;
} yajl_val_s_u_number;


typedef struct {
  const char **keys;                     
  yajl_val *values;                        
  size_t len;                                  
} yajl_val_s_u_object;


typedef struct {
  yajl_val *values;                          
  size_t len;                           
} yajl_val_s_u_array;



#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_yajljsonJNI_YAJL_1MAX_1DEPTH_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(128);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1alloc_1funcs_1malloc_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  yajl_alloc_funcs *arg1 = (yajl_alloc_funcs *) 0 ;
  yajl_malloc_func arg2 = (yajl_malloc_func) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_alloc_funcs **)&jarg1; 
  arg2 = *(yajl_malloc_func *)&jarg2; 
  if (arg1) (arg1)->malloc = arg2;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1alloc_1funcs_1malloc_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_alloc_funcs *arg1 = (yajl_alloc_funcs *) 0 ;
  yajl_malloc_func result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_alloc_funcs **)&jarg1; 
  result = (yajl_malloc_func) ((arg1)->malloc);
  *(yajl_malloc_func *)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1alloc_1funcs_1realloc_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  yajl_alloc_funcs *arg1 = (yajl_alloc_funcs *) 0 ;
  yajl_realloc_func arg2 = (yajl_realloc_func) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_alloc_funcs **)&jarg1; 
  arg2 = *(yajl_realloc_func *)&jarg2; 
  if (arg1) (arg1)->realloc = arg2;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1alloc_1funcs_1realloc_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_alloc_funcs *arg1 = (yajl_alloc_funcs *) 0 ;
  yajl_realloc_func result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_alloc_funcs **)&jarg1; 
  result = (yajl_realloc_func) ((arg1)->realloc);
  *(yajl_realloc_func *)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1alloc_1funcs_1free_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  yajl_alloc_funcs *arg1 = (yajl_alloc_funcs *) 0 ;
  yajl_free_func arg2 = (yajl_free_func) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_alloc_funcs **)&jarg1; 
  arg2 = *(yajl_free_func *)&jarg2; 
  if (arg1) (arg1)->free = arg2;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1alloc_1funcs_1free_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_alloc_funcs *arg1 = (yajl_alloc_funcs *) 0 ;
  yajl_free_func result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_alloc_funcs **)&jarg1; 
  result = (yajl_free_func) ((arg1)->free);
  *(yajl_free_func *)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1alloc_1funcs_1ctx_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  yajl_alloc_funcs *arg1 = (yajl_alloc_funcs *) 0 ;
  void *arg2 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_alloc_funcs **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  if (arg1) (arg1)->ctx = arg2;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1alloc_1funcs_1ctx_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_alloc_funcs *arg1 = (yajl_alloc_funcs *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_alloc_funcs **)&jarg1; 
  result = (void *) ((arg1)->ctx);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_new_1yajl_1alloc_1funcs(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  yajl_alloc_funcs *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_alloc_funcs *)calloc(1, sizeof(yajl_alloc_funcs));
  *(yajl_alloc_funcs **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_delete_1yajl_1alloc_1funcs(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  yajl_alloc_funcs *arg1 = (yajl_alloc_funcs *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_alloc_funcs **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1gen_1status_1ok_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  yajl_gen_status result;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_gen_status)yajl_gen_status_ok;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1gen_1beautify_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  yajl_gen_option result;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_gen_option)yajl_gen_beautify;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1gen_1indent_1string_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  yajl_gen_option result;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_gen_option)yajl_gen_indent_string;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1gen_1print_1callback_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  yajl_gen_option result;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_gen_option)yajl_gen_print_callback;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1gen_1validate_1utf8_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  yajl_gen_option result;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_gen_option)yajl_gen_validate_utf8;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1gen_1escape_1solidus_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  yajl_gen_option result;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_gen_option)yajl_gen_escape_solidus;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1gen_1config(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jint jresult = 0 ;
  yajl_gen arg1 = (yajl_gen) 0 ;
  yajl_gen_option arg2 ;
  void *arg3 = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_gen *)&jarg1; 
  arg2 = (yajl_gen_option)jarg2; 
  result = (int)yajl_gen_config(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1gen_1alloc(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_alloc_funcs *arg1 = (yajl_alloc_funcs *) 0 ;
  yajl_gen result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_alloc_funcs **)&jarg1; 
  result = (yajl_gen)yajl_gen_alloc((yajl_alloc_funcs const *)arg1);
  *(yajl_gen *)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1gen_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  yajl_gen arg1 = (yajl_gen) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_gen *)&jarg1; 
  yajl_gen_free(arg1);
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1gen_1integer(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  yajl_gen arg1 = (yajl_gen) 0 ;
  long long arg2 ;
  yajl_gen_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_gen *)&jarg1; 
  arg2 = (long long)jarg2; 
  result = (yajl_gen_status)yajl_gen_integer(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1gen_1double(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2) {
  jint jresult = 0 ;
  yajl_gen arg1 = (yajl_gen) 0 ;
  double arg2 ;
  yajl_gen_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_gen *)&jarg1; 
  arg2 = (double)jarg2; 
  result = (yajl_gen_status)yajl_gen_double(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1gen_1number(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  yajl_gen arg1 = (yajl_gen) 0 ;
  char *arg2 = (char *) 0 ;
  size_t arg3 ;
  yajl_gen_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_gen *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (size_t)jarg3; 
  result = (yajl_gen_status)yajl_gen_number(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1gen_1string(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  yajl_gen arg1 = (yajl_gen) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  size_t arg3 ;
  yajl_gen_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_gen *)&jarg1; 
  arg2 = *(unsigned char **)&jarg2; 
  arg3 = (size_t)jarg3; 
  result = (yajl_gen_status)yajl_gen_string(arg1,(unsigned char const *)arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1gen_1null(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  yajl_gen arg1 = (yajl_gen) 0 ;
  yajl_gen_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_gen *)&jarg1; 
  result = (yajl_gen_status)yajl_gen_null(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1gen_1bool(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jint jresult = 0 ;
  yajl_gen arg1 = (yajl_gen) 0 ;
  int arg2 ;
  yajl_gen_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_gen *)&jarg1; 
  arg2 = (int)jarg2; 
  result = (yajl_gen_status)yajl_gen_bool(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1gen_1map_1open(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  yajl_gen arg1 = (yajl_gen) 0 ;
  yajl_gen_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_gen *)&jarg1; 
  result = (yajl_gen_status)yajl_gen_map_open(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1gen_1map_1close(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  yajl_gen arg1 = (yajl_gen) 0 ;
  yajl_gen_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_gen *)&jarg1; 
  result = (yajl_gen_status)yajl_gen_map_close(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1gen_1array_1open(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  yajl_gen arg1 = (yajl_gen) 0 ;
  yajl_gen_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_gen *)&jarg1; 
  result = (yajl_gen_status)yajl_gen_array_open(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1gen_1array_1close(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  yajl_gen arg1 = (yajl_gen) 0 ;
  yajl_gen_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_gen *)&jarg1; 
  result = (yajl_gen_status)yajl_gen_array_close(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1gen_1get_1buf(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  yajl_gen arg1 = (yajl_gen) 0 ;
  unsigned char **arg2 = (unsigned char **) 0 ;
  size_t *arg3 = (size_t *) 0 ;
  yajl_gen_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_gen *)&jarg1; 
  arg2 = *(unsigned char ***)&jarg2; 
  arg3 = *(size_t **)&jarg3; 
  result = (yajl_gen_status)yajl_gen_get_buf(arg1,(unsigned char const **)arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1gen_1clear(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  yajl_gen arg1 = (yajl_gen) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_gen *)&jarg1; 
  yajl_gen_clear(arg1);
}


SWIGEXPORT jstring JNICALL Java_yajljsonJNI_yajl_1status_1to_1string(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jstring jresult = 0 ;
  yajl_status arg1 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (yajl_status)jarg1; 
  result = (char *)yajl_status_to_string(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1callbacks_1yajl_1null_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  int (*arg2)(void *) = (int (*)(void *)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_callbacks **)&jarg1; 
  arg2 = *(int (**)(void *))&jarg2; 
  if (arg1) (arg1)->yajl_null = arg2;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1callbacks_1yajl_1null_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  int (*result)(void *) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_callbacks **)&jarg1; 
  result = (int (*)(void *)) ((arg1)->yajl_null);
  *(int (**)(void *))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1callbacks_1yajl_1boolean_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  int (*arg2)(void *,int) = (int (*)(void *,int)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_callbacks **)&jarg1; 
  arg2 = *(int (**)(void *,int))&jarg2; 
  if (arg1) (arg1)->yajl_boolean = arg2;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1callbacks_1yajl_1boolean_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  int (*result)(void *,int) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_callbacks **)&jarg1; 
  result = (int (*)(void *,int)) ((arg1)->yajl_boolean);
  *(int (**)(void *,int))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1callbacks_1yajl_1integer_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  int (*arg2)(void *,long long) = (int (*)(void *,long long)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_callbacks **)&jarg1; 
  arg2 = *(int (**)(void *,long long))&jarg2; 
  if (arg1) (arg1)->yajl_integer = arg2;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1callbacks_1yajl_1integer_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  int (*result)(void *,long long) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_callbacks **)&jarg1; 
  result = (int (*)(void *,long long)) ((arg1)->yajl_integer);
  *(int (**)(void *,long long))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1callbacks_1yajl_1double_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  int (*arg2)(void *,double) = (int (*)(void *,double)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_callbacks **)&jarg1; 
  arg2 = *(int (**)(void *,double))&jarg2; 
  if (arg1) (arg1)->yajl_double = arg2;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1callbacks_1yajl_1double_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  int (*result)(void *,double) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_callbacks **)&jarg1; 
  result = (int (*)(void *,double)) ((arg1)->yajl_double);
  *(int (**)(void *,double))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1callbacks_1yajl_1number_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  int (*arg2)(void *,char const *,size_t) = (int (*)(void *,char const *,size_t)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_callbacks **)&jarg1; 
  arg2 = *(int (**)(void *,char const *,size_t))&jarg2; 
  if (arg1) (arg1)->yajl_number = arg2;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1callbacks_1yajl_1number_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  int (*result)(void *,char const *,size_t) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_callbacks **)&jarg1; 
  result = (int (*)(void *,char const *,size_t)) ((arg1)->yajl_number);
  *(int (**)(void *,char const *,size_t))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1callbacks_1yajl_1string_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  int (*arg2)(void *,unsigned char const *,size_t) = (int (*)(void *,unsigned char const *,size_t)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_callbacks **)&jarg1; 
  arg2 = *(int (**)(void *,unsigned char const *,size_t))&jarg2; 
  if (arg1) (arg1)->yajl_string = arg2;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1callbacks_1yajl_1string_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  int (*result)(void *,unsigned char const *,size_t) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_callbacks **)&jarg1; 
  result = (int (*)(void *,unsigned char const *,size_t)) ((arg1)->yajl_string);
  *(int (**)(void *,unsigned char const *,size_t))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1callbacks_1yajl_1start_1map_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  int (*arg2)(void *) = (int (*)(void *)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_callbacks **)&jarg1; 
  arg2 = *(int (**)(void *))&jarg2; 
  if (arg1) (arg1)->yajl_start_map = arg2;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1callbacks_1yajl_1start_1map_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  int (*result)(void *) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_callbacks **)&jarg1; 
  result = (int (*)(void *)) ((arg1)->yajl_start_map);
  *(int (**)(void *))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1callbacks_1yajl_1map_1key_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  int (*arg2)(void *,unsigned char const *,size_t) = (int (*)(void *,unsigned char const *,size_t)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_callbacks **)&jarg1; 
  arg2 = *(int (**)(void *,unsigned char const *,size_t))&jarg2; 
  if (arg1) (arg1)->yajl_map_key = arg2;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1callbacks_1yajl_1map_1key_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  int (*result)(void *,unsigned char const *,size_t) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_callbacks **)&jarg1; 
  result = (int (*)(void *,unsigned char const *,size_t)) ((arg1)->yajl_map_key);
  *(int (**)(void *,unsigned char const *,size_t))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1callbacks_1yajl_1end_1map_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  int (*arg2)(void *) = (int (*)(void *)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_callbacks **)&jarg1; 
  arg2 = *(int (**)(void *))&jarg2; 
  if (arg1) (arg1)->yajl_end_map = arg2;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1callbacks_1yajl_1end_1map_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  int (*result)(void *) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_callbacks **)&jarg1; 
  result = (int (*)(void *)) ((arg1)->yajl_end_map);
  *(int (**)(void *))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1callbacks_1yajl_1start_1array_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  int (*arg2)(void *) = (int (*)(void *)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_callbacks **)&jarg1; 
  arg2 = *(int (**)(void *))&jarg2; 
  if (arg1) (arg1)->yajl_start_array = arg2;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1callbacks_1yajl_1start_1array_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  int (*result)(void *) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_callbacks **)&jarg1; 
  result = (int (*)(void *)) ((arg1)->yajl_start_array);
  *(int (**)(void *))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1callbacks_1yajl_1end_1array_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  int (*arg2)(void *) = (int (*)(void *)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_callbacks **)&jarg1; 
  arg2 = *(int (**)(void *))&jarg2; 
  if (arg1) (arg1)->yajl_end_array = arg2;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1callbacks_1yajl_1end_1array_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  int (*result)(void *) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_callbacks **)&jarg1; 
  result = (int (*)(void *)) ((arg1)->yajl_end_array);
  *(int (**)(void *))&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_new_1yajl_1callbacks(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  yajl_callbacks *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_callbacks *)calloc(1, sizeof(yajl_callbacks));
  *(yajl_callbacks **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_delete_1yajl_1callbacks(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_callbacks **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1alloc(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jlong jarg3) {
  jlong jresult = 0 ;
  yajl_callbacks *arg1 = (yajl_callbacks *) 0 ;
  yajl_alloc_funcs *arg2 = (yajl_alloc_funcs *) 0 ;
  void *arg3 = (void *) 0 ;
  yajl_handle result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(yajl_callbacks **)&jarg1; 
  arg2 = *(yajl_alloc_funcs **)&jarg2; 
  arg3 = *(void **)&jarg3; 
  result = (yajl_handle)yajl_alloc((yajl_callbacks const *)arg1,arg2,arg3);
  *(yajl_handle *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1allow_1comments_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  yajl_option result;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_option)yajl_allow_comments;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1dont_1validate_1strings_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  yajl_option result;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_option)yajl_dont_validate_strings;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1allow_1trailing_1garbage_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  yajl_option result;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_option)yajl_allow_trailing_garbage;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1allow_1multiple_1values_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  yajl_option result;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_option)yajl_allow_multiple_values;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1allow_1partial_1values_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  yajl_option result;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_option)yajl_allow_partial_values;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1config(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jint jresult = 0 ;
  yajl_handle arg1 = (yajl_handle) 0 ;
  yajl_option arg2 ;
  void *arg3 = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_handle *)&jarg1; 
  arg2 = (yajl_option)jarg2; 
  result = (int)yajl_config(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  yajl_handle arg1 = (yajl_handle) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_handle *)&jarg1; 
  yajl_free(arg1);
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1parse(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  yajl_handle arg1 = (yajl_handle) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  size_t arg3 ;
  yajl_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_handle *)&jarg1; 
  arg2 = *(unsigned char **)&jarg2; 
  arg3 = (size_t)jarg3; 
  result = (yajl_status)yajl_parse(arg1,(unsigned char const *)arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1complete_1parse(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  yajl_handle arg1 = (yajl_handle) 0 ;
  yajl_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_handle *)&jarg1; 
  result = (yajl_status)yajl_complete_parse(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1get_1error(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  yajl_handle arg1 = (yajl_handle) 0 ;
  int arg2 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  size_t arg4 ;
  unsigned char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_handle *)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(unsigned char **)&jarg3; 
  arg4 = (size_t)jarg4; 
  result = (unsigned char *)yajl_get_error(arg1,arg2,(unsigned char const *)arg3,arg4);
  *(unsigned char **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1get_1bytes_1consumed(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  yajl_handle arg1 = (yajl_handle) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_handle *)&jarg1; 
  result = yajl_get_bytes_consumed(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1free_1error(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  yajl_handle arg1 = (yajl_handle) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_handle *)&jarg1; 
  arg2 = *(unsigned char **)&jarg2; 
  yajl_free_error(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_YAJL_1TREE_1H_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1t_1string_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  yajl_type result;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_type)yajl_t_string;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1t_1number_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  yajl_type result;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_type)yajl_t_number;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1t_1object_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  yajl_type result;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_type)yajl_t_object;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1t_1array_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  yajl_type result;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_type)yajl_t_array;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1t_1true_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  yajl_type result;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_type)yajl_t_true;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1t_1false_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  yajl_type result;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_type)yajl_t_false;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1t_1null_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  yajl_type result;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_type)yajl_t_null;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1t_1any_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  yajl_type result;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_type)yajl_t_any;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_YAJL_1NUMBER_1INT_1VALID_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(0x01);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_YAJL_1NUMBER_1DOUBLE_1VALID_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(0x02);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1val_1s_1type_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct yajl_val_s *arg1 = (struct yajl_val_s *) 0 ;
  yajl_type arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct yajl_val_s **)&jarg1; 
  arg2 = (yajl_type)jarg2; 
  if (arg1) (arg1)->type = arg2;
}


SWIGEXPORT jint JNICALL Java_yajljsonJNI_yajl_1val_1s_1type_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct yajl_val_s *arg1 = (struct yajl_val_s *) 0 ;
  yajl_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct yajl_val_s **)&jarg1; 
  result = (yajl_type) ((arg1)->type);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct yajl_val_s *arg1 = (struct yajl_val_s *) 0 ;
  yajl_val_s_u *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct yajl_val_s **)&jarg1; 
  result = (yajl_val_s_u *)& ((arg1)->u);
  *(yajl_val_s_u **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_new_1yajl_1val_1s(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct yajl_val_s *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct yajl_val_s *)calloc(1, sizeof(struct yajl_val_s));
  *(struct yajl_val_s **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_delete_1yajl_1val_1s(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct yajl_val_s *arg1 = (struct yajl_val_s *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct yajl_val_s **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1string_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  yajl_val_s_u *arg1 = (yajl_val_s_u *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val_s_u **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->string);
    if (arg2) {
      arg1->string = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->string, (const char *)arg2);
    } else {
      arg1->string = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1string_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  yajl_val_s_u *arg1 = (yajl_val_s_u *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val_s_u **)&jarg1; 
  result = (char *) ((arg1)->string);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1number_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_val_s_u *arg1 = (yajl_val_s_u *) 0 ;
  yajl_val_s_u_number *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val_s_u **)&jarg1; 
  result = (yajl_val_s_u_number *)& ((arg1)->number);
  *(yajl_val_s_u_number **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1object_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_val_s_u *arg1 = (yajl_val_s_u *) 0 ;
  yajl_val_s_u_object *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val_s_u **)&jarg1; 
  result = (yajl_val_s_u_object *)& ((arg1)->object);
  *(yajl_val_s_u_object **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1array_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_val_s_u *arg1 = (yajl_val_s_u *) 0 ;
  yajl_val_s_u_array *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val_s_u **)&jarg1; 
  result = (yajl_val_s_u_array *)& ((arg1)->array);
  *(yajl_val_s_u_array **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_new_1yajl_1val_1s_1u(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  yajl_val_s_u *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_val_s_u *)calloc(1, sizeof(yajl_val_s_u));
  *(yajl_val_s_u **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_delete_1yajl_1val_1s_1u(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  yajl_val_s_u *arg1 = (yajl_val_s_u *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_val_s_u **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1array_1values_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  yajl_val_s_u_array *arg1 = (yajl_val_s_u_array *) 0 ;
  yajl_val *arg2 = (yajl_val *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val_s_u_array **)&jarg1; 
  arg2 = *(yajl_val **)&jarg2; 
  if (arg1) (arg1)->values = arg2;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1array_1values_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_val_s_u_array *arg1 = (yajl_val_s_u_array *) 0 ;
  yajl_val *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val_s_u_array **)&jarg1; 
  result = (yajl_val *) ((arg1)->values);
  *(yajl_val **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1array_1len_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  yajl_val_s_u_array *arg1 = (yajl_val_s_u_array *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val_s_u_array **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->len = arg2;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1array_1len_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_val_s_u_array *arg1 = (yajl_val_s_u_array *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val_s_u_array **)&jarg1; 
  result =  ((arg1)->len);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_new_1yajl_1val_1s_1u_1array(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  yajl_val_s_u_array *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_val_s_u_array *)calloc(1, sizeof(yajl_val_s_u_array));
  *(yajl_val_s_u_array **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_delete_1yajl_1val_1s_1u_1array(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  yajl_val_s_u_array *arg1 = (yajl_val_s_u_array *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_val_s_u_array **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1object_1keys_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  yajl_val_s_u_object *arg1 = (yajl_val_s_u_object *) 0 ;
  char **arg2 = (char **) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val_s_u_object **)&jarg1; 
  arg2 = *(char ***)&jarg2; 
  if (arg1) (arg1)->keys = (char const **)arg2;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1object_1keys_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_val_s_u_object *arg1 = (yajl_val_s_u_object *) 0 ;
  char **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val_s_u_object **)&jarg1; 
  result = (char **) ((arg1)->keys);
  *(char ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1object_1values_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  yajl_val_s_u_object *arg1 = (yajl_val_s_u_object *) 0 ;
  yajl_val *arg2 = (yajl_val *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val_s_u_object **)&jarg1; 
  arg2 = *(yajl_val **)&jarg2; 
  if (arg1) (arg1)->values = arg2;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1object_1values_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_val_s_u_object *arg1 = (yajl_val_s_u_object *) 0 ;
  yajl_val *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val_s_u_object **)&jarg1; 
  result = (yajl_val *) ((arg1)->values);
  *(yajl_val **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1object_1len_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  yajl_val_s_u_object *arg1 = (yajl_val_s_u_object *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val_s_u_object **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->len = arg2;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1object_1len_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_val_s_u_object *arg1 = (yajl_val_s_u_object *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val_s_u_object **)&jarg1; 
  result =  ((arg1)->len);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_new_1yajl_1val_1s_1u_1object(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  yajl_val_s_u_object *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_val_s_u_object *)calloc(1, sizeof(yajl_val_s_u_object));
  *(yajl_val_s_u_object **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_delete_1yajl_1val_1s_1u_1object(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  yajl_val_s_u_object *arg1 = (yajl_val_s_u_object *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_val_s_u_object **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1number_1i_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  yajl_val_s_u_number *arg1 = (yajl_val_s_u_number *) 0 ;
  long long arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val_s_u_number **)&jarg1; 
  arg2 = (long long)jarg2; 
  if (arg1) (arg1)->i = arg2;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1number_1i_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_val_s_u_number *arg1 = (yajl_val_s_u_number *) 0 ;
  long long result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val_s_u_number **)&jarg1; 
  result = (long long) ((arg1)->i);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1number_1d_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  yajl_val_s_u_number *arg1 = (yajl_val_s_u_number *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val_s_u_number **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->d = arg2;
}


SWIGEXPORT jdouble JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1number_1d_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  yajl_val_s_u_number *arg1 = (yajl_val_s_u_number *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val_s_u_number **)&jarg1; 
  result = (double) ((arg1)->d);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1number_1r_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  yajl_val_s_u_number *arg1 = (yajl_val_s_u_number *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val_s_u_number **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->r);
    if (arg2) {
      arg1->r = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->r, (const char *)arg2);
    } else {
      arg1->r = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1number_1r_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  yajl_val_s_u_number *arg1 = (yajl_val_s_u_number *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val_s_u_number **)&jarg1; 
  result = (char *) ((arg1)->r);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1number_1flags_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  yajl_val_s_u_number *arg1 = (yajl_val_s_u_number *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val_s_u_number **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->flags = arg2;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1val_1s_1u_1number_1flags_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  yajl_val_s_u_number *arg1 = (yajl_val_s_u_number *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val_s_u_number **)&jarg1; 
  result = (unsigned int) ((arg1)->flags);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_new_1yajl_1val_1s_1u_1number(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  yajl_val_s_u_number *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (yajl_val_s_u_number *)calloc(1, sizeof(yajl_val_s_u_number));
  *(yajl_val_s_u_number **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_delete_1yajl_1val_1s_1u_1number(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  yajl_val_s_u_number *arg1 = (yajl_val_s_u_number *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(yajl_val_s_u_number **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1tree_1parse(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  size_t arg3 ;
  yajl_val result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (size_t)jarg3; 
  result = (yajl_val)yajl_tree_parse((char const *)arg1,arg2,arg3);
  *(yajl_val *)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_yajljsonJNI_yajl_1tree_1free(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  yajl_val arg1 = (yajl_val) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val *)&jarg1; 
  yajl_tree_free(arg1);
}


SWIGEXPORT jlong JNICALL Java_yajljsonJNI_yajl_1tree_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jint jarg3) {
  jlong jresult = 0 ;
  yajl_val arg1 = (yajl_val) 0 ;
  char **arg2 = (char **) 0 ;
  yajl_type arg3 ;
  yajl_val result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(yajl_val *)&jarg1; 
  arg2 = *(char ***)&jarg2; 
  arg3 = (yajl_type)jarg3; 
  result = (yajl_val)yajl_tree_get(arg1,(char const **)arg2,arg3);
  *(yajl_val *)&jresult = result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

